install: gradle wrapper --gradle-version 4.2
language: java
jdk:
  - oraclejdk8
services:
  - postgresql
addons:
  postgresql: "9.5"
before_script:
  - psql -c 'create database product_hunter;' -U postgres
  - psql -c '\c product_hunter;' -U postgres
  - psql -c 'grant all on schema public to postgres;' -U postgres
  - psql -c 'CREATE TABLE products (id BIGSERIAL PRIMARY KEY, title VARCHAR NOT NULL, country VARCHAR NOT NULL, dt_update TIMESTAMP WITHOUT TIME ZONE, price NUMERIC, price_discount NUMERIC, uuid UUID NOT NULL);' -U postgres
  - psql -c 'SELECT count(id) FROM products;' -U postgres
  - psql -c 'CREATE UNIQUE INDEX product_uuid_idx ON products (uuid);' -U postgres
script:
  - ./gradlew build --scan -s -i
