install: gradle wrapper --gradle-version 4.2
language: java
jdk:
  - oraclejdk8
services:
  - postgresql
before_script:
  - psql -c 'create database product_hunter;' -U postgres
  - psql -c 'CREATE SCHEMA product_hunter_test;' -U postgres
script:
  - ./gradlew test --scan -s
  - ./gradlew build --scan -s