install: gradle wrapper --gradle-version 4.2
language: java
jdk:
  - oraclejdk8
services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - psql -c 'create database product_hunter;' -U postgres
script:
  - ./gradlew test --scan -s
dist: trusty